# Games
# source_url: The url from the game's embed code
# project_url: The url to the game's page
games:
  - name: "Siege of Syracuse"
    embed_id: "2693906"
    project_url: "https://divingavran.itch.io/siege-of-syracuse"

  - name: "Double Check"
    embed_id: "2658120"
    project_url: "https://divingavran.itch.io/double-check"

# Social Media
# href: link to the account
# icon: FontAwesome 5 icon name (https://fontawesome.com/v5/search?o=r&m=free)
accounts:
  - name: "GitHub"
    href: "https://github.com/divin"
    icon: "fab fa-github"

  - name: "YouTube"
    href: "https://www.youtube.com/@divingavran"
    icon: "fab fa-youtube"

  - name: "Itch.io"
    href: "https://divingavran.itch.io"
    icon: "fab fa-itch-io"

  - name: "Bandcamp"
    href: "https://divin.bandcamp.com"
    icon: "fab fa-bandcamp"

  - name: "SoundCloud"
    href: "https://soundcloud.com/divingavran"
    icon: "fab fa-soundcloud"
