title: "Divin Gavran"

home:
  greeting: Hi. I'm Divin.
  subgreeting: A Data Scientist.
  description: I'm always involved in exciting projects, continuously seeking opportunities to learn and express my creativity.

about:
  greeting: I'm Divin.
  image: "/images/about.jpg"
  description: |
    I'm a data scientist with a background in physics who loves unraveling insights from complex data.<br><br>
    When I'm not crunching numbers, you'll find me immersed in software and game development, creating music, exploring art, and diving into the fascinating realms of AI.<br><br>
    My passion lies in machine learning, natural language processing, and computer vision, where I get to blend science and creativity to push the boundaries of what's possible.<br><br>
    Down below you'll find more information about me. If you'd like to get in touch, feel free to send me a message!

projects:
  greeting: "My Projects."
  description: "Here are some of the projects I've been working on recently."

navigation:
  - title: "Home"
    href: "/"

  - title: "About"
    href: "/about"
  
  - title: "Projects"
    href: "/projects"
  
  #- title: "Contact"
  #  href: "/contact"
  
projects-list:
  - name: "Blob Out!"
    href: "https://divingavran.itch.io/blob-out"
    image: "/images/blob-out.png"
    created: "2022-06-18"
    updated: "2022-06-18"
  
  - name: "Flappy Raven"
    href: "https://divingavran.itch.io/flappy-raven"
    image: "/images/flappy-raven.png"
    created: "2023-02-22"
    updated: "2023-02-22"
  
  - name: "The Royal Game of Ur"
    href: "https://divingavran.itch.io/the-royal-game-of-ur"
    image: "/images/the-royal-game-of-ur.png"
    created: "2022-07-17"
    updated: "2022-07-17"

# Social Media
# url: link to the account
# icon: FontAwesome 5 icon name (https://fontawesome.com/v5/search?o=r&m=free)
social-media:

  - name: "GitHub"
    url: "https://github.com/divin"
    icon: "fab fa-github"

  - name: "YouTube"
    url: "https://www.youtube.com/@divingavran"
    icon: "fab fa-youtube"

  - name: "Itch.io"
    url: "https://divingavran.itch.io"
    icon: "fab fa-itch-io"
  
  - name: "Patreon"
    url: "https://patreon.com/divingavran"
    icon: "fab fa-patreon"

  - name: "Bandcamp"
    url: "https://divin.bandcamp.com"
    icon: "fab fa-bandcamp"

  - name: "SoundCloud"
    url: "https://soundcloud.com/divingavran"
    icon: "fab fa-soundcloud"

background:
  - name: "Data Scientist"
    icon: "fas fa-briefcase"
    from: "2023"
    to: "today"
    description: |
      As an experienced Python developer with a solid background in statistical analysis, my focus is on extracting actionable insights from complex datasets.<br><br>
      Leveraging my applied knowledge, I specialize in building sophisticated machine learning models, and proactively extend existing codebases to automate the analysis process even further.
  
  - name: "Physics, M. Sc."
    icon: "fas fa-graduation-cap"
    from: "2022"
    to: "2023"
    description: |
      For my Master's thesis, I developed expertise in automating experimental data analysis using deep learning techniques.<br><br> 
      I focused on improving the performance of an existing object recognition model based on Faster R-CNN by using hyperparameter optimization to achieve better detection results of diffraction patterns in experimental data.<br><br>
      Additionally, I designed and created a smaller YOLO-based model that was capable of performing similar tasks as the original model, but with significantly faster processing times.

  - name: "Physics, B. Sc."
    icon: "fas fa-graduation-cap"
    from: "2016"
    to: "2022"
    description: |
      Through my studies in physics, I developed a solid foundation in both fundamental and advanced topics.<br><br>
      As I continued to pursue my education, I focused on specializing in computational physics, taking computer science courses and developing strong proficiency in Python.<br><br>
      For my Bachelor's thesis, I conducted research on the formation of planets on a protoplanetary disk, gaining valuable insights into the migration of planets driven by the disk torques and offering a unique perspective on these phenomena.

# Skills in percent
skills:
  languages:
    - name: German
      value: 100
    
    - name: English
      value: 85
    
    - name: Japanese
      value: 25
  
  coding:
    - name: Python
      value: 100
    
    - name: HTML
      value: 80
    
    - name: CSS
      value: 60

    - name: SQL
      value: 60
    
    - name: GScript
      value: 80
    
  python:
    - name: NumPy
      value: 90
    
    - name: Pandas
      value: 90
    
    - name: Matplotlib
      value: 90
    
    - name: Seaborn
      value: 70
    
    - name: Scikit-Learn
      value: 80
    
    - name: PyTorch
      value: 60

  tools:
    - name: Git
      value: 75

    - name: Linux
      value: 75
    
    - name: Docker
      value: 40

    - name: Jupyter
      value: 100
    
    - name: VSCode
      value: 100
    
    - name: Blender
      value: 25
    
    - name: Logic Pro
      value: 80
    
    - name: Final Cut
      value: 50
    
    - name: Godot
      value: 80


website:
  font_size: "1.0rem"
  font_family: "Lato"
  font_weight: "400"
  max_width: "1280px"
  
  colors:
    text: "#dbeadf"
    background: "#334c3a"
    primary: "#316d42"
    secondary: "#183520"
    accent: "#c1b19c"