# Games
# embed_id: The url from the game's embed code
# project_url: The url to the game's page
games:
  - name: "Siege of Syracuse"
    embed_id: "2693906"
    project_url: "https://divingavran.itch.io/siege-of-syracuse"

  - name: "Double Check"
    embed_id: "2658120"
    project_url: "https://divingavran.itch.io/double-check"

# Apps
# embed_id: The url from the apps embed code
# project_url: The url to the apps page
apps:
  - name: "memento mori"
    embed_id: "3490922"
    project_url: "https://divingavran.itch.io/memento-mori"

# Music
# - url: link to the music on Bandcamp
music:
  - url: https://divin.bandcamp.com/track/smack
  - url: https://divin.bandcamp.com/track/election-day
  - url: https://divin.bandcamp.com/track/come-on-feet
  - url: https://divin.bandcamp.com/track/back-in-india
  - url: https://divin.bandcamp.com/track/outer-space
  - url: https://divin.bandcamp.com/track/super-bright
  - url: https://divin.bandcamp.com/track/not-sure-why
  - url: https://divin.bandcamp.com/track/hooked
  - url: https://divin.bandcamp.com/track/deep-dip
  - url: https://divin.bandcamp.com/track/funkey
  - url: https://divin.bandcamp.com/album/a-i-made-this
  - url: https://divin.bandcamp.com/track/--15
  - url: https://divin.bandcamp.com/album/-
  - url: https://divin.bandcamp.com/album/--2
  - url: https://divin.bandcamp.com/album/--4
  - url: https://divin.bandcamp.com/album/--5

# Social Media
# name: name of the account
# href: link to the account
# icon: FontAwesome 5 icon name (https://fontawesome.com/v5/search?o=r&m=free)
accounts:
  - name: "GitHub"
    href: "https://github.com/divin"
    icon: "fab fa-github"

  - name: "YouTube"
    href: "https://www.youtube.com/@divingavran"
    icon: "fab fa-youtube"

  - name: "Itch.io"
    href: "https://divingavran.itch.io"
    icon: "fab fa-itch-io"

  - name: "Bandcamp"
    href: "https://divin.bandcamp.com"
    icon: "fab fa-bandcamp"

  - name: "SoundCloud"
    href: "https://soundcloud.com/divingavran"
    icon: "fab fa-soundcloud"
