services:
  divingavran:
    container_name: divingavran
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - io-stack_cloudflare
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.divingavran.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.divingavran.loadbalancer.server.port=8080"

networks:
  io-stack_cloudflare:
    external: true
