[project]
name = "divingavran.com"
description = "My personal website."
license = { text = "MIT" }
requires-python = ">=3.10"
authors = [
  { name = "Divin Gavran" },
]

[tool.black]
line-length = 88

[tool.isort]
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true
skip = [
    ".web",
    "__pycache__",
    "assets"
]

[tool.flake8]
max-line-length = 88
max-complexity = 18
exclude = [
    ".git",
    "__pycache__",
    "assets",
    ".web",
    "__init__.py",
]
extend-ignore = "E203"
per-file-ignores = [
    "website/website.py:F601"
]