[[items]]
title = "Yoru"
artist = "Divin"
date = "2025-09-28"
kind = "music"
url = "https://divin.bandcamp.com/track/yoru"

[[items]]
title = "Neon Mirage"
artist = "Divin"
date = "2025-09-14"
kind = "music"
url = "https://divin.bandcamp.com/track/neon-mirage"

[[items]]
title = "東京"
artist = "Divin"
date = "2025-07-27"
kind = "music"
url = "https://divin.bandcamp.com/track/--16"

[[items]]
title = "Vibrant Mirage"
artist = "Divin"
date = "2025-06-29"
kind = "music"
url = "https://divin.bandcamp.com/track/vibrant-mirage"

[[items]]
title = "Sunday Afternoon"
artist = "Divin"
date = "2025-06-22"
kind = "music"
url = "https://divin.bandcamp.com/track/sunday-afternoon"

[[items]]
title = "Samba"
artist = "Karasu-san"
date = "2025-06-15"
kind = "music"
url = "https://divin.bandcamp.com/track/samba"

[[items]]
title = "Jazztastic"
artist = "Divin"
date = "2025-06-01"
kind = "music"
url = "https://divin.bandcamp.com/track/jazztastic"

[[items]]
title = "Jazzy Bob"
artist = "Divin"
date = "2025-05-25"
kind = "music"
url = "https://divin.bandcamp.com/track/jazzy-bob"

[[items]]
title = "IDFM"
artist = "Divin"
date = "2025-05-18"
kind = "music"
url = "https://divin.bandcamp.com/track/idfm"

[[items]]
title = "Elevator Funk"
artist = "Divin"
date = "2025-05-11"
kind = "music"
url = "https://divin.bandcamp.com/track/elevator-funk"

[[items]]
title = "Brasil"
artist = "Karasu-san"
date = "2025-05-04"
kind = "music"
url = "https://divin.bandcamp.com/track/brasil"

[[items]]
title = "Smack"
artist = "Divin"
date = "2025-04-27"
kind = "music"
url = "https://divin.bandcamp.com/track/smack"

[[items]]
title = "Election Day"
artist = "Divin"
date = "2025-04-20"
kind = "music"
url = "https://divin.bandcamp.com/track/election-day"

[[items]]
title = "Come On Feet"
artist = "Divin"
date = "2025-04-13"
kind = "music"
url = "https://divin.bandcamp.com/track/come-on-feet"

[[items]]
title = "Back in India"
artist = "Divin"
date = "2025-04-06"
kind = "music"
url = "https://divin.bandcamp.com/track/back-in-india"

[[items]]
title = "Outer Space"
artist = "Divin"
date = "2025-03-30"
kind = "music"
url = "https://divin.bandcamp.com/track/outer-space"

[[items]]
title = "Super Bright"
artist = "Divin"
date = "2025-03-23"
kind = "music"
url = "https://divin.bandcamp.com/track/super-bright"

[[items]]
title = "Not sure why"
artist = "Divin"
date = "2025-03-16"
kind = "music"
url = "https://divin.bandcamp.com/track/not-sure-why"

[[items]]
title = "Hooked"
artist = "Divin"
date = "2025-03-09"
kind = "music"
url = "https://divin.bandcamp.com/track/hooked"

[[items]]
title = "Deep Dip"
artist = "Divin"
date = "2025-03-02"
kind = "music"
url = "https://divin.bandcamp.com/track/deep-dip"

[[items]]
title = "Funkey"
artist = "Divin"
date = "2025-02-23"
kind = "music"
url = "https://divin.bandcamp.com/track/funkey"

[[items]]
title = "(A)I Made This"
artist = "Divin"
date = "2025-02-15"
kind = "music"
url = "https://divin.bandcamp.com/album/a-i-made-this"

[[items]]
title = "インド"
artist = "Divin"
date = "2025-02-15"
kind = "music"
url = "https://divin.bandcamp.com/track/--15"

[[items]]
title = "雨の夜"
artist = "Divin"
date = "2024-07-18"
kind = "music"
url = "https://divin.bandcamp.com/album/-"

[[items]]
title = "どっぷり"
artist = "Divin"
date = "2024-07-16"
kind = "music"
url = "https://divin.bandcamp.com/album/--2"

[[items]]
title = "踊り"
artist = "Divin"
date = "2024-07-15"
kind = "music"
url = "https://divin.bandcamp.com/album/--4"

[[items]]
title = "うるさい"
artist = "Divin"
date = "2023-03-29"
kind = "music"
url = "https://divin.bandcamp.com/album/--5"
