name: Build Site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.11 # Set up the required version of Python

    steps:
      - name: Check out the repository
        uses: actions/checkout@master

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install staticjinja

      - name: Build site
        run: |
          python build.py

      - name: Upload build folder
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: build

      - name: Download Website Artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: build

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "build site"
          git push
