name: Build Site
on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    env:
      PYTHON_VERSION: 3.11 # Set up the required version of Python

    steps:
      - name: Check out the repository
        uses: actions/checkout@master

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install staticjinja

      - name: Build site
        run: |
          python build.py

      - name: Commit the build
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: build site
          add_options: "-f"
          push_options: "--force"

      - name: Push changes
        run: |
          git push
