name: Deploy to Railway (Production)

on:
  push:
    tags:
      - "*" # Triggers on any tag push

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: divingavran
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PRODUCTION }}
    steps:
      - uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            See the changelog or commit history for details.
          draft: false
          prerelease: false

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }} --ci --environment production
