name: Deploy to Railway (Stage)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: divingavran
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_STAGE }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }} --ci --environment stage
